name: Code Compliance

on: [pull_request]

jobs:
  test-code-compliance:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install make
      run: sudo apt-get install make

    - name: build image
      run: make build

    - name: flake8 test
      run: make test
